### PR TITLE
Replace ceilDiv with clojure.math/ceil

### LINKED ISSUE #165: console/app-handler throws error for jdk < 18
Describe the bug
--------
Error is thrown when loading client namespace using `console/app-handler`
Error:
```
 :cause No matching method ceilDiv found taking 2 args for class java.lang.Math
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling . at (goose/brokers/redis/console/pages/enqueued.clj:36:57).
   :data #:clojure.error{:phase :compile-syntax-check, :line 36, :column 57, :source goose/brokers/redis/console/pages/enqueued.clj, :symbol .}
   :at [clojure.lang.Compiler analyzeSeq Compiler.java 7132]}
  {:type java.lang.IllegalArgumentException
   :message No matching method ceilDiv found taking 2 args for class java.lang.Math
   :at [clojure.lang.Compiler$StaticMethodExpr <init> Compiler.java 1687]}]}
```

To Reproduce
--------
Load the following client-namespace with jvm < 18

```clojure
(ns client
  (:require
    [compojure.core :refer [context defroutes]]
    [compojure.route :as route]
    [goose.brokers.redis.broker :as redis]
    [goose.brokers.rmq.broker :as rmq]
    [goose.console :as console]

    [ring.adapter.jetty :as jetty]))


(defonce server (atom nil))

(def redis-producer (redis/new-producer redis/default-opts))
;;(def rabbitmq-producer (rmq/new-producer rmq/default-opts))

(defroutes goose-routes
           (context "/goose" []
                    (partial console/app-handler {:broker       redis-producer
                                                  :app-name     "Goose's client"
                                                  :route-prefix "/goose"}))
           (route/not-found "<h1>Page not found </h1>"))

(defn start-server []
  (reset! server (jetty/run-jetty goose-routes {:port  3004
                                                :join? false})))

(defn stop-server []
  (when-let [s @server]
    (.stop s)
    (println s "Stopped")))

(start-server)
```

Versions
--------
1. Goose: 0.5.0
2. Clojure: 1.11.0

Screenshots
--------

### PR DESCRIPTION
**Pull request by alishamohanty**
Fixes #165

Changes involve:
- replace Math/ceilDiv with clojure.math/ceil (supported since Java8)
- format the doc string for [app-handler](https://cljdoc.org/d/com.nilenso/goose/0.5.0/api/goose.console)
- add default-console-opts (Goose philosophy for having sane defaults)
- remove middlewares, view-components and handler functions from cljdocs for now
    - to simplify only viewing necessary apis 
  - above functions will be removed from cljdocs, but will still be available to use

### CODE REVIEW

File: src/goose/defaults.clj [hunk 1]
```diff
@@ -78,6 +78,8 @@
 
 ;;; ======== Console ========
 
+(def route-prefix "/goose")
+(def app-name "Goose console")
```
Comment (siripr4) [inline src/goose/defaults.clj:82]: nit: should this be Title Case?

File: src/goose/console.clj [hunk 2]
```diff
@@ -1,60 +1,63 @@
...
             [hiccup.page :refer [html5 include-css include-js]]
             [ring.middleware.keyword-params :as ring-keyword-params]
             [ring.middleware.params :as ring-params]
             [ring.util.response :as response]))
 
 ;; Page handlers
-(defn load-css
-  "Load static css file"
+(defn ^:no-doc load-css
+      "Load goose's static css file"
```
Comment (siripr4) [inline src/goose/console.clj:13]: question: Shouldn't this be "Goose console's static ..."?

Similar comment for the `load-js`'s docstring as well

File: src/goose/console.clj [hunk 3]
```diff
@@ -1,60 +1,63 @@
...
+   a map `data` and return hiccup data representing part of a webpage
 
-  ### Usage
-   ```Clojure
-   (def job [job]
-        [:p {:class \"job\"} (:id job)])
+   ### Usage
+   ```clojure
+    (defn job [j]
+      [:div (:id j)])
```
Comment (siripr4) [inline src/goose/console.clj:55]: question(non-blocking): I don't understand this change, can you explain what it is?

**Review by siripr4 — APPROVED** [review]

File: src/goose/console.clj (hunk 3 above)
Comment (alishamohanty) [reply src/goose/console.clj:55]: This is an improved example for what a component accepted by layout function looks like.
If you notice, the previous definition was wrong, and I added a `div` instead of `:p`.
