### PR TITLE
Dead jobs API to operate on >1 job

### LINKED ISSUE #169: Add dead jobs console API
Add dead jobs console API to 
- delete/replay multiple jobs
- view jobs within a range.

### Why showcase job in decreasing order of died-at?
Since recent dead jobs are usually more relevant and important to investigate and troubleshoot. If a job has failed recently, it's likely that the issue or cause of the failure is still present or relevant, and addressing it promptly is more important than looking at older failures that may have been resolved or become less relevant over time.

### PR DESCRIPTION
**Pull request by alishamohanty**
Closes #169

### CODE REVIEW

File: src/goose/brokers/redis/api/dead_jobs.clj [hunk 1]
```diff
@@ -21,10 +21,18 @@
...
+(defn replay-job [redis-conn & jobs]
+  (let [sorted-set d/prefixed-dead-queue
+        scores (apply redis-cmds/sorted-set-scores redis-conn sorted-set jobs)
+        jobs-with-valid-scores (->> (mapv vector jobs scores)
+                                    (remove #(nil? (second %)))
+                                    (mapv first))
+        valid-jobs-count (count jobs-with-valid-scores)]
+    (when (< 0 valid-jobs-count)
+      (let [response (redis-cmds/sorted-set->ready-queue redis-conn sorted-set jobs-with-valid-scores job/ready-or-retry-queue)]
+        (if (= 1 valid-jobs-count)
```
[the remark this answers is not in the document]
Comment (alishamohanty) [reply src/goose/brokers/redis/api/dead_jobs.clj]: As per our previous discussion, I have created separate api to replay multiple jobs.

File: test/goose/factories.clj [hunk 2]
```diff
@@ -38,14 +38,16 @@
     cron-opts))
 
 (defn create-dead-job [& [overrides]]
-  (let [error-state {:state {:error           "Error"
-                             :last-retried-at (u/epoch-time-ms),
-                             :first-failed-at 1701344365468,
-                             :retry-count     27,
+  (let [now (u/epoch-time-ms)
+        error-state {:state {:error           "Error"
+                             :last-retried-at now
```
Comment (alishamohanty) [inline test/goose/factories.clj:43]: Missed out  adding `died-at` for a failed job. Check [here](https://github.com/nilenso/goose/blob/26e80d9b3f392cd9e08bb2790e503bc1f89d854e/src/goose/brokers/rmq/retry.clj#L33).

File: src/goose/brokers/redis/api/dead_jobs.clj [hunk 3]
```diff
@@ -21,24 +21,41 @@
         match? (fn [job] (= (:id job) id))]
     (first (find-by-pattern redis-conn match? limit))))
 
+;; TODO: Return job instead of redis txn
 (defn replay-job [redis-conn job]
   (let [sorted-set d/prefixed-dead-queue]
-    (when (redis-cmds/sorted-set-score redis-conn sorted-set job)
+    (when (not-every? nil? (redis-cmds/sorted-set-scores redis-conn sorted-set job))
```
Comment (siripr4) [inline src/goose/brokers/redis/api/dead_jobs.clj:27]: question: What has changed here? Shouldn't this function be unchanged since console uses the newer function?

File: src/goose/brokers/redis/api/scheduled_jobs.clj [hunk 4]
```diff
@@ -17,7 +17,7 @@
 
 (defn prioritise-execution [redis-conn job]
   (let [sorted-set d/prefixed-schedule-queue]
-    (when (redis-cmds/sorted-set-score redis-conn sorted-set job)
+    (when (not-every? nil? (redis-cmds/sorted-set-scores redis-conn sorted-set job))
```
Comment (siripr4) [inline src/goose/brokers/redis/api/scheduled_jobs.clj:20]: Same question as the other comment

File: src/goose/brokers/redis/api/dead_jobs.clj (hunk 3 above)
Comment (alishamohanty) [reply src/goose/brokers/redis/api/dead_jobs.clj:27]: This is a different change.
I have refactored `sorted-set-score` to sorted-set-scores` to take >=1 job/s at redis commands layer.

**Review by siripr4 — APPROVED** [review]
